export const filterList = [{
	code: "01000000",
	title: "基本信息",
	value: "基本信息",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "01010000",
		title: "年龄",
		value: "年龄",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "客户年龄",
		list: [{
			code: "01010100",
			title: "<22",
			value: "<22",
			colField: "AGE_GROUP",
			name: "年龄#<22",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01010200",
			title: "[22,40)",
			value: "[22,40)",
			colField: "AGE_GROUP",
			name: "年龄#[22,40)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01010300",
			title: "[40,60)",
			value: "[40,60)",
			colField: "AGE_GROUP",
			name: "年龄#[40,60)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01010400",
			title: "≥60",
			value: "≥60",
			colField: "AGE_GROUP",
			name: "年龄#≥60",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01010500",
			title: "自定义",
			value: "",
			colField: "AGE_GROUP",
			name: "年龄",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "01020000",
		title: "性别",
		value: "性别",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "客户性别",
		list: [{
			code: "01020100",
			title: "男",
			value: "男",
			colField: "GND",
			name: "性别#男",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01020200",
			title: "女",
			value: "女",
			colField: "GND",
			name: "性别#女",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "01030000",
		title: "客户标志",
		value: "客户标志",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "根据客户在我行办理业务情况进行的客户分群",
		list: [{
			code: "01030100",
			title: "代发",
			value: "代发",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "根据客户在我行是否有代发记录、是否符合有效代发口径判断",
			list: [{
				code: "01030101",
				title: "有效",
				value: "有效",
				colField: "AGENT_CST_FLG",
				name: "客户标志#代发#有效",
				minValue: "",
				maxValue: "",
				remark: "符合有效代发口径的客户",
				list: []
			}, {
				code: "01030102",
				title: "无效",
				value: "无效",
				colField: "AGENT_CST_FLG",
				name: "客户标志#代发#无效",
				minValue: "",
				maxValue: "",
				remark: "在我行有代发记录，但不符合有效代发口径",
				list: []
			}, {
				code: "01030103",
				title: "非代发",
				value: "非代发",
				colField: "AGENT_CST_FLG",
				name: "客户标志#代发#非代发",
				minValue: "",
				maxValue: "",
				remark: "在我行从未有过代发记录的客户",
				list: []
			}]
		}, {
			code: "01030200",
			title: "贷款",
			value: "贷款",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "根据客户在我行当前或历史是否有授信记录判断",
			list: [{
				code: "01030201",
				title: "历史",
				value: "历史",
				colField: "LOAN_CST_FLG",
				name: "客户标志#贷款#历史",
				minValue: "",
				maxValue: "",
				remark: "在我行曾有授信记录，但当前授信额度为0",
				list: []
			}, {
				code: "01030202",
				title: "当前",
				value: "当前",
				colField: "LOAN_CST_FLG",
				name: "客户标志#贷款#当前",
				minValue: "",
				maxValue: "",
				remark: "在我行当前授信额度大于0",
				list: []
			}, {
				code: "01030203",
				title: "非贷款",
				value: "非贷款",
				colField: "LOAN_CST_FLG",
				name: "客户标志#贷款#非贷款",
				minValue: "",
				maxValue: "",
				remark: "在我行从未有过授信额度",
				list: []
			}]
		}, {
			code: "01030300",
			title: "财富",
			value: "财富",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "根据客户在我行当前或历史资产月日均是否大于5万元判断",
			list: [{
				code: "01030301",
				title: "历史",
				value: "历史",
				colField: "VIP_CST_FLG",
				name: "客户标志#财富#历史",
				minValue: "",
				maxValue: "",
				remark: "客户历史月日均达到5万元及以上，但上月月日均小于5万元",
				list: []
			}, {
				code: "01030302",
				title: "当前",
				value: "当前",
				colField: "VIP_CST_FLG",
				name: "客户标志#财富#当前",
				minValue: "",
				maxValue: "",
				remark: "客户上月月日均大于等于5万元",
				list: []
			}, {
				code: "01030303",
				title: "非财富",
				value: "非财富",
				colField: "VIP_CST_FLG",
				name: "客户标志#财富#非财富",
				minValue: "",
				maxValue: "",
				remark: "客户历史与上月月日均均小于5万元",
				list: []
			}]
		}, {
			code: "01030400",
			title: "收单",
			value: "收单",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "根据客户在我行具体收单情况判断",
			list: [{
				code: "01030401",
				title: "小微",
				value: "小微",
				colField: "RICH_CST_FLG",
				name: "客户标志#收单#小微",
				minValue: "",
				maxValue: "",
				remark: "我行收单商户，名下收单均为小微商户，即未录入营业执照号",
				list: []
			}, {
				code: "01030402",
				title: "普通",
				value: "普通",
				colField: "RICH_CST_FLG",
				name: "客户标志#收单#普通",
				minValue: "",
				maxValue: "",
				remark: "我行收单商户，名下收单存在普通商户，即系统中有营业执照号",
				list: []
			}, {
				code: "01030403",
				title: "对公",
				value: "对公",
				colField: "RICH_CST_FLG",
				name: "客户标志#收单#对公",
				minValue: "",
				maxValue: "",
				remark: "我行收单商户，名下收单客户号以C开头",
				list: []
			}, {
				code: "01030404",
				title: "非收单",
				value: "非收单",
				colField: "RICH_CST_FLG",
				name: "客户标志#收单#非收单",
				minValue: "",
				maxValue: "",
				remark: "非我行收单商户",
				list: []
			}]
		}, {
			code: "01030500",
			title: "个体工商户",
			value: "个体工商户",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "根据客户在我行具体收单情况判断",
			list: [{
				code: "01030501",
				title: "是",
				value: "是",
				colField: "INDV_CST_FLG",
				name: "客户标志#个体工商户#是",
				minValue: "",
				maxValue: "",
				remark: "取系统中有个体工商户标志的客户",
				list: []
			}, {
				code: "01030502",
				title: "否",
				value: "否",
				colField: "INDV_CST_FLG",
				name: "客户标志#个体工商户#否",
				minValue: "",
				maxValue: "",
				remark: "取系统中无个体工商户标志的客户",
				list: []
			}]
		}]
	}, {
		code: "01040000",
		title: "服务等级",
		value: "服务等级",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "上月广义AUM月日均对应等级（私行：600万以上，钻石：200万-600万，白金：100万-200万，金卡：30万-100万，理财：5万-30万，大众：1万-5万，未达标：1万以下）",
		list: [{
			code: "01040100",
			title: "私行",
			value: "私行",
			colField: "SRV_LVL",
			name: "服务等级#私行",
			minValue: "",
			maxValue: "",
			remark: "客户上月广义AUM月日均600万以上",
			list: []
		}, {
			code: "01040200",
			title: "钻石",
			value: "钻石",
			colField: "SRV_LVL",
			name: "服务等级#钻石",
			minValue: "",
			maxValue: "",
			remark: "客户上月广义AUM月日均处于[200万,600万)区间",
			list: []
		}, {
			code: "01040300",
			title: "白金",
			value: "白金",
			colField: "SRV_LVL",
			name: "服务等级#白金",
			minValue: "",
			maxValue: "",
			remark: "客户上月广义AUM月日均处于[100万,200万)区间",
			list: []
		}, {
			code: "01040400",
			title: "金卡",
			value: "金卡",
			colField: "SRV_LVL",
			name: "服务等级#金卡",
			minValue: "",
			maxValue: "",
			remark: "客户上月广义AUM月日均处于[30万,100万)区间",
			list: []
		}, {
			code: "01040500",
			title: "理财",
			value: "理财",
			colField: "SRV_LVL",
			name: "服务等级#理财",
			minValue: "",
			maxValue: "",
			remark: "客户上月广义AUM月日均处于[5万,30万)区间",
			list: []
		}, {
			code: "01040600",
			title: "大众",
			value: "大众",
			colField: "SRV_LVL",
			name: "服务等级#大众",
			minValue: "",
			maxValue: "",
			remark: "客户上月广义AUM月日均处于[1万,5万)区间",
			list: []
		}, {
			code: "01040700",
			title: "未达标",
			value: "未达标",
			colField: "SRV_LVL",
			name: "服务等级#未达标",
			minValue: "",
			maxValue: "",
			remark: "客户上月广义AUM月日均处于1万元以下",
			list: []
		}]
	}, {
		code: "01050000",
		title: "风险评级",
		value: "风险评级",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "客户在我行最新风险评级（暂时取理财）",
		list: [{
			code: "01050100",
			title: "R1",
			value: "R1",
			colField: "CFT_RISK_RATING",
			name: "风险评级#R1",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01050200",
			title: "R2",
			value: "R2",
			colField: "CFT_RISK_RATING",
			name: "风险评级#R2",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01050300",
			title: "R3",
			value: "R3",
			colField: "CFT_RISK_RATING",
			name: "风险评级#R3",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01050400",
			title: "R4",
			value: "R4",
			colField: "CFT_RISK_RATING",
			name: "风险评级#R4",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "01050500",
			title: "R5",
			value: "R5",
			colField: "CFT_RISK_RATING",
			name: "风险评级#R5",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "01060000",
		title: "开户时长",
		value: "",
		colField: "OPAC_DURAN",
		name: "开户时长",
		minValue: "",
		maxValue: "",
		remark: "客户在我行开立首个个人账户距今时间差",
		list: []
	}]
}, {
	code: "02000000",
	title: "授信指标",
	value: "授信指标",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "02010000",
		title: "授信额度",
		value: "授信额度",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "客户在我行当前的有效授信额度",
		list: [{
			code: "02010100",
			title: "全部",
			value: "全部",
			colField: "CRDT_LIMIT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户在我行当前的有效授信额度",
			list: [{
				code: "02010101",
				title: "≤10万",
				value: "≤10万",
				colField: "",
				name: "授信额度#全部#≤10万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010102",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "授信额度#全部#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010103",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "授信额度#全部#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010104",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "授信额度#全部#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010105",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "授信额度#全部#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010106",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信额度#全部",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02010200",
			title: "信用",
			value: "信用",
			colField: "CRDT_LIMIT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户在我行当前的有效授信额度",
			list: [{
				code: "02010201",
				title: "≤10万",
				value: "≤10万",
				colField: "",
				name: "授信额度#信用#≤10万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010202",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "授信额度#信用#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010203",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "授信额度#信用#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010204",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "授信额度#信用#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010205",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "授信额度#信用#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010206",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信额度#信用",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02010300",
			title: "保证",
			value: "保证",
			colField: "CRDT_LIMIT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户在我行当前的有效授信额度",
			list: [{
				code: "02010301",
				title: "≤10万",
				value: "≤10万",
				colField: "",
				name: "授信额度#保证#≤10万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010302",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "授信额度#保证#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010303",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "授信额度#保证#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010304",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "授信额度#保证#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010305",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "授信额度#保证#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010306",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信额度#保证",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02010400",
			title: "抵押",
			value: "抵押",
			colField: "CRDT_LIMIT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户在我行当前的有效授信额度",
			list: [{
				code: "02010401",
				title: "≤10万",
				value: "≤10万",
				colField: "",
				name: "授信额度#抵押#≤10万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010402",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "授信额度#抵押#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010403",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "授信额度#抵押#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010404",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "授信额度#抵押#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010405",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "授信额度#抵押#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010406",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信额度#抵押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02010500",
			title: "质押",
			value: "质押",
			colField: "CRDT_LIMIT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户在我行当前的有效授信额度",
			list: [{
				code: "02010501",
				title: "≤10万",
				value: "≤10万",
				colField: "",
				name: "授信额度#质押#≤10万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010502",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "授信额度#质押#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010503",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "授信额度#质押#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010504",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "授信额度#质押#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010505",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "授信额度#质押#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02010506",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信额度#质押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}]
	}, {
		code: "02020000",
		title: "是否用信",
		value: "是否用信",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "客户当前是否有用信（我行贷款）",
		list: [{
			code: "02020100",
			title: "全部",
			value: "全部",
			colField: "IS_CRDT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户当前是否有用信（我行贷款）",
			list: [{
				code: "02020101",
				title: "是",
				value: "是",
				colField: "",
				name: "是否用信#全部#是",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02020102",
				title: "否",
				value: "否",
				colField: "",
				name: "是否用信#全部#否",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02020200",
			title: "信用",
			value: "信用",
			colField: "IS_CRDT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户当前是否有用信（我行贷款）",
			list: [{
				code: "02020201",
				title: "是",
				value: "是",
				colField: "",
				name: "是否用信#信用#是",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02020202",
				title: "否",
				value: "否",
				colField: "IS_CRDT",
				name: "是否用信#信用#否",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02020300",
			title: "保证",
			value: "保证",
			colField: "IS_CRDT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户当前是否有用信（我行贷款）",
			list: [{
				code: "02020301",
				title: "是",
				value: "是",
				colField: "",
				name: "是否用信#保证#是",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02020302",
				title: "否",
				value: "否",
				colField: "",
				name: "是否用信#保证#否",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02020400",
			title: "抵押",
			value: "抵押",
			colField: "IS_CRDT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户当前是否有用信（我行贷款）",
			list: [{
				code: "02020401",
				title: "是",
				value: "是",
				colField: "",
				name: "是否用信#抵押#是",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02020402",
				title: "否",
				value: "否",
				colField: "",
				name: "是否用信#抵押#否",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02020500",
			title: "质押",
			value: "质押",
			colField: "IS_CRDT",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户当前是否有用信（我行贷款）",
			list: [{
				code: "02020501",
				title: "是",
				value: "是",
				colField: "",
				name: "是否用信#质押#是",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02020502",
				title: "否",
				value: "否",
				colField: "",
				name: "是否用信#质押#否",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}]
	}, {
		code: "02030000",
		title: "贷款月日均",
		value: "贷款月日均",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "上月每日的贷款余额累计值与上月天数之比",
		list: [{
			code: "02030100",
			title: "全部",
			value: "全部",
			colField: "LOAN_MONTH_AVG",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户上月贷款月日均",
			list: []
		}, {
			code: "02030200",
			title: "信用",
			value: "信用",
			colField: "LOAN_MONTH_AVG",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户上月贷款月日均",
			list: []
		}, {
			code: "02030300",
			title: "保证",
			value: "保证",
			colField: "LOAN_MONTH_AVG",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户上月贷款月日均",
			list: []
		}, {
			code: "02030400",
			title: "抵押",
			value: "抵押",
			colField: "LOAN_MONTH_AVG",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户上月贷款月日均",
			list: []
		}, {
			code: "02030500",
			title: "质押",
			value: "质押",
			colField: "LOAN_MONTH_AVG",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，客户上月贷款月日均",
			list: []
		}]
	}, {
		code: "02040000",
		title: "授信失效时间",
		value: "授信失效时间",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "选中贷款类别下，取剩余多少日授信失效",
		list: [{
			code: "02040100",
			title: "全部",
			value: "全部",
			colField: "CRDT_EXP_DAY",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，取剩余多少日授信失效",
			list: [{
				code: "02040101",
				title: "≤10天",
				value: "≤10天",
				colField: "",
				name: "授信失效时间#全部#≤10天",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040102",
				title: "(10天,30天]",
				value: "(10天,30天]",
				colField: "",
				name: "授信失效时间#全部#(10天,30天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040103",
				title: "(30天,60天]",
				value: "(30天,60天]",
				colField: "",
				name: "授信失效时间#全部#(30天,60天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040104",
				title: "(60天,90天]",
				value: "(60天,90天]",
				colField: "",
				name: "授信失效时间#全部#(60天,90天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040105",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信失效时间#全部",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02040200",
			title: "信用",
			value: "信用",
			colField: "CRDT_EXP_DAY",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，取剩余多少日授信失效",
			list: [{
				code: "02040201",
				title: "≤10天",
				value: "≤10天",
				colField: "",
				name: "授信失效时间#信用#≤10天",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040202",
				title: "(10天,30天]",
				value: "(10天,30天]",
				colField: "",
				name: "授信失效时间#信用#(10天,30天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040203",
				title: "(30天,60天]",
				value: "(30天,60天]",
				colField: "",
				name: "授信失效时间#信用#(30天,60天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040204",
				title: "(60天,90天]",
				value: "(60天,90天]",
				colField: "",
				name: "授信失效时间#信用#(60天,90天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040205",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信失效时间#信用",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02040300",
			title: "保证",
			value: "保证",
			colField: "CRDT_EXP_DAY",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，取剩余多少日授信失效",
			list: [{
				code: "02040301",
				title: "≤10天",
				value: "≤10天",
				colField: "",
				name: "授信失效时间#保证#≤10天",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040302",
				title: "(10天,30天]",
				value: "(10天,30天]",
				colField: "",
				name: "授信失效时间#保证#(10天,30天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040303",
				title: "(30天,60天]",
				value: "(30天,60天]",
				colField: "",
				name: "授信失效时间#保证#(30天,60天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040304",
				title: "(60天,90天]",
				value: "(60天,90天]",
				colField: "",
				name: "授信失效时间#保证#(60天,90天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040305",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信失效时间#保证",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02040400",
			title: "抵押",
			value: "抵押",
			colField: "CRDT_EXP_DAY",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，取剩余多少日授信失效",
			list: [{
				code: "02040401",
				title: "≤10天",
				value: "≤10天",
				colField: "",
				name: "授信失效时间#抵押#≤10天",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040402",
				title: "(10天,30天]",
				value: "(10天,30天]",
				colField: "",
				name: "授信失效时间#抵押#(10天,30天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040403",
				title: "(30天,60天]",
				value: "(30天,60天]",
				colField: "",
				name: "授信失效时间#抵押#(30天,60天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040404",
				title: "(60天,90天]",
				value: "(60天,90天]",
				colField: "",
				name: "授信失效时间#抵押#(60天,90天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040405",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信失效时间#抵押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02040500",
			title: "质押",
			value: "质押",
			colField: "CRDT_EXP_DAY",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，取剩余多少日授信失效",
			list: [{
				code: "02040501",
				title: "≤10天",
				value: "≤10天",
				colField: "",
				name: "授信失效时间#质押#≤10天",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040502",
				title: "(10天,30天]",
				value: "(10天,30天]",
				colField: "",
				name: "授信失效时间#质押#(10天,30天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040503",
				title: "(30天,60天]",
				value: "(30天,60天]",
				colField: "",
				name: "授信失效时间#质押#(30天,60天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040504",
				title: "(60天,90天]",
				value: "(60天,90天]",
				colField: "",
				name: "授信失效时间#质押#(60天,90天]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02040505",
				title: "自定义",
				value: "",
				colField: "",
				name: "授信失效时间#质押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}]
	}, {
		code: "02050000",
		title: "客户用信率",
		value: "客户用信率",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "贷款余额与授信额度之比",
		list: [{
			code: "02050100",
			title: "全部",
			value: "全部",
			colField: "CST_CRDT_RATE",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，贷款余额与授信额度之比",
			list: [{
				code: "02050101",
				title: "0",
				value: "0",
				colField: "",
				name: "客户用信率#全部#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050102",
				title: "(0,20%]",
				value: "(0,20%]",
				colField: "",
				name: "客户用信率#全部#(0,20%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050103",
				title: "(20%,40%]",
				value: "(20%,40%]",
				colField: "",
				name: "客户用信率#全部#(20%,40%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050104",
				title: "(40%,60%]",
				value: "(40%,60%]",
				colField: "",
				name: "客户用信率#全部#(40%,60%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050105",
				title: "＞60%",
				value: "＞60%",
				colField: "",
				name: "客户用信率#全部#＞60%",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050106",
				title: "自定义",
				value: "",
				colField: "",
				name: "客户用信率#全部",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02050200",
			title: "信用",
			value: "信用",
			colField: "CST_CRDT_RATE",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，贷款余额与授信额度之比",
			list: [{
				code: "02050201",
				title: "0",
				value: "0",
				colField: "",
				name: "客户用信率#信用#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050202",
				title: "(0,20%]",
				value: "(0,20%]",
				colField: "",
				name: "客户用信率#信用#(0,20%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050203",
				title: "(20%,40%]",
				value: "(20%,40%]",
				colField: "",
				name: "客户用信率#信用#(20%,40%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050204",
				title: "(40%,60%]",
				value: "(40%,60%]",
				colField: "",
				name: "客户用信率#信用#(40%,60%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050205",
				title: "＞60%",
				value: "＞60%",
				colField: "",
				name: "客户用信率#信用#＞60%",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050206",
				title: "自定义",
				value: "",
				colField: "",
				name: "客户用信率#信用",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02050300",
			title: "保证",
			value: "保证",
			colField: "CST_CRDT_RATE",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，贷款余额与授信额度之比",
			list: [{
				code: "02050301",
				title: "0",
				value: "0",
				colField: "",
				name: "客户用信率#保证#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050302",
				title: "(0,20%]",
				value: "(0,20%]",
				colField: "",
				name: "客户用信率#保证#(0,20%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050303",
				title: "(20%,40%]",
				value: "(20%,40%]",
				colField: "",
				name: "客户用信率#保证#(20%,40%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050304",
				title: "(40%,60%]",
				value: "(40%,60%]",
				colField: "",
				name: "客户用信率#保证#(40%,60%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050305",
				title: "＞60%",
				value: "＞60%",
				colField: "",
				name: "客户用信率#保证#＞60%",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050306",
				title: "自定义",
				value: "",
				colField: "",
				name: "客户用信率#保证",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02050400",
			title: "抵押",
			value: "抵押",
			colField: "CST_CRDT_RATE",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，贷款余额与授信额度之比",
			list: [{
				code: "02050401",
				title: "0",
				value: "0",
				colField: "",
				name: "客户用信率#抵押#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050402",
				title: "(0,20%]",
				value: "(0,20%]",
				colField: "",
				name: "客户用信率#抵押#(0,20%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050403",
				title: "(20%,40%]",
				value: "(20%,40%]",
				colField: "",
				name: "客户用信率#抵押#(20%,40%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050404",
				title: "(40%,60%]",
				value: "(40%,60%]",
				colField: "",
				name: "客户用信率#抵押#(40%,60%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050405",
				title: "＞60%",
				value: "＞60%",
				colField: "",
				name: "客户用信率#抵押#＞60%",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050406",
				title: "自定义",
				value: "",
				colField: "",
				name: "客户用信率#抵押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02050500",
			title: "质押",
			value: "质押",
			colField: "CST_CRDT_RATE",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "选中贷款类别下，贷款余额与授信额度之比",
			list: [{
				code: "02050501",
				title: "0",
				value: "0",
				colField: "",
				name: "客户用信率#质押#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050502",
				title: "(0,20%]",
				value: "(0,20%]",
				colField: "",
				name: "客户用信率#质押#(0,20%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050503",
				title: "(20%,40%]",
				value: "(20%,40%]",
				colField: "",
				name: "客户用信率#质押#(20%,40%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050504",
				title: "(40%,60%]",
				value: "(40%,60%]",
				colField: "",
				name: "客户用信率#质押#(40%,60%]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050505",
				title: "＞60%",
				value: "＞60%",
				colField: "",
				name: "客户用信率#质押#＞60%",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02050506",
				title: "自定义",
				value: "",
				colField: "",
				name: "客户用信率#质押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}]
	}, {
		code: "02060000",
		title: "贷款活期留存率",
		value: "贷款活期留存率",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "广义活期上月月日均与贷款上月月日均之比",
		list: [{
			code: "02060100",
			title: "≤0.5%",
			value: "≤0.5%",
			colField: "LOAN_CURR_DPSIT_RATE",
			name: "贷款活期留存率#≤0.5%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02060200",
			title: "(0.5%,1.5%]",
			value: "(0.5%,1.5%]",
			colField: "LOAN_CURR_DPSIT_RATE",
			name: "贷款活期留存率#(0.5%,1.5%]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02060300",
			title: "(1.5%,5%]",
			value: "(1.5%,5%]",
			colField: "LOAN_CURR_DPSIT_RATE",
			name: "贷款活期留存率#(1.5%,5%]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02060400",
			title: "＞5%",
			value: "＞5%",
			colField: "LOAN_CURR_DPSIT_RATE",
			name: "贷款活期留存率#＞5%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02060500",
			title: "自定义",
			value: "",
			colField: "LOAN_CURR_DPSIT_RATE",
			name: "贷款活期留存率",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "02070000",
		title: "贷款AUM留存率",
		value: "贷款AUM留存率",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "广义AUM上月月日均与贷款上月月日均之比",
		list: [{
			code: "02070100",
			title: "≤0.5%",
			value: "≤0.5%",
			colField: "LOAN_AUM_RATE",
			name: "贷款AUM留存率#≤0.5%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02070200",
			title: "(0.5%,1.5%]",
			value: "(0.5%,1.5%]",
			colField: "LOAN_AUM_RATE",
			name: "贷款AUM留存率#(0.5%,1.5%]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02070300",
			title: "(1.5%,5%]",
			value: "(1.5%,5%]",
			colField: "LOAN_AUM_RATE",
			name: "贷款AUM留存率#(1.5%,5%]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02070400",
			title: "＞5%",
			value: "＞5%",
			colField: "LOAN_AUM_RATE",
			name: "贷款AUM留存率#＞5%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02070500",
			title: "自定义",
			value: "",
			colField: "LOAN_AUM_RATE",
			name: "贷款AUM留存率",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "02080000",
		title: "贷款综合贡献得分",
		value: "贷款综合贡献得分",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "从定价（40%)、AUM月日均占贷款余额比率（40%）、客户合作产品类型（10%）、客户人行征信位置排名（10%）四个维度反映客户对我行的贡献水平。总得分等于四个维度分数加总，分值越高，对我行贡献度越高。",
		list: [{
			code: "02080100",
			title: "≤20",
			value: "≤20",
			colField: "LOAN_CMPRH_CONTRI_SCRO",
			name: "贷款综合贡献得分#≤20",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02080200",
			title: "(20,30]",
			value: "(20,30]",
			colField: "LOAN_CMPRH_CONTRI_SCRO",
			name: "贷款综合贡献得分#(20,30]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02080300",
			title: "(30,40]",
			value: "(30,40]",
			colField: "LOAN_CMPRH_CONTRI_SCRO",
			name: "贷款综合贡献得分#(30,40]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02080400",
			title: "(40,50]",
			value: "(40,50]",
			colField: "LOAN_CMPRH_CONTRI_SCRO",
			name: "贷款综合贡献得分#(40,50]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02080500",
			title: "＞50",
			value: "＞50",
			colField: "LOAN_CMPRH_CONTRI_SCRO",
			name: "贷款综合贡献得分#＞50",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02080600",
			title: "自定义",
			value: "",
			colField: "LOAN_CMPRH_CONTRI_SCRO",
			name: "贷款综合贡献得分",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "02090000",
		title: "贷款综合贡献应用",
		value: "贷款综合贡献应用",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "从定价（40%)、AUM月日均占贷款余额比率（40%）、客户合作产品类型（10%）、客户人行征信位置排名（10%）四个维度反映客户对客户贡献水平并进行分值排序得到",
		list: [{
			code: "02090100",
			title: "卓越客户",
			value: "卓越客户",
			colField: "LOAN_CMPRH_CONTRI",
			name: "贷款综合贡献应用#卓越客户",
			minValue: "",
			maxValue: "",
			remark: "贷款贡献度全行排名前20％（含）的客户",
			list: []
		}, {
			code: "02090200",
			title: "潜力客户",
			value: "潜力客户",
			colField: "LOAN_CMPRH_CONTRI",
			name: "贷款综合贡献应用#潜力客户",
			minValue: "",
			maxValue: "",
			remark: "贷款贡献度全行排名20%-90%（含）的客户",
			list: []
		}, {
			code: "02090300",
			title: "预警客户",
			value: "预警客户",
			colField: "LOAN_CMPRH_CONTRI",
			name: "贷款综合贡献应用#预警客户",
			minValue: "",
			maxValue: "",
			remark: "贷款贡献度全行排名后5%-10%的客户",
			list: []
		}, {
			code: "02090400",
			title: "退出客户",
			value: "退出客户",
			colField: "LOAN_CMPRH_CONTRI",
			name: "贷款综合贡献应用#退出客户",
			minValue: "",
			maxValue: "",
			remark: "贷款贡献度全行排名后5%的客户",
			list: []
		}]
	}, {
		code: "02100000",
		title: "他行授信额度",
		value: "他行授信额度",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取最近一次我行线上查询的客户征信报告上他行授信未到期的进行汇总，若无线上查询记录，则此项为空",
		list: [{
			code: "02100100",
			title: "全部",
			value: "全部",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "取最近一次线上征信报告上授信到期日晚于当前日期的所有贷款汇总",
			list: [{
				code: "02100101",
				title: "0",
				value: "0",
				colField: "",
				name: "他行授信额度#全部#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100102",
				title: "(0,10万]",
				value: "(0,10万]",
				colField: "",
				name: "他行授信额度#全部#(0,10万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100103",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "他行授信额度#全部#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100104",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "他行授信额度#全部#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100105",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "他行授信额度#全部#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100106",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "他行授信额度#全部#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100107",
				title: "自定义",
				value: "",
				colField: "",
				name: "他行授信额度#全部",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02100200",
			title: "信用",
			value: "信用",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "取最近一次线上征信报告上授信到期日晚于当前日期的所有贷款汇总",
			list: [{
				code: "02100201",
				title: "0",
				value: "0",
				colField: "",
				name: "他行授信额度#信用#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100202",
				title: "(0,10万]",
				value: "(0,10万]",
				colField: "",
				name: "他行授信额度#信用#(0,10万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100203",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "他行授信额度#信用#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100204",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "他行授信额度#信用#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100205",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "他行授信额度#信用#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100206",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "他行授信额度#信用#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100207",
				title: "自定义",
				value: "",
				colField: "",
				name: "他行授信额度#信用",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02100300",
			title: "保证",
			value: "保证",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "取最近一次线上征信报告上授信到期日晚于当前日期的所有贷款汇总",
			list: [{
				code: "02100301",
				title: "0",
				value: "0",
				colField: "",
				name: "他行授信额度#保证#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100302",
				title: "(0,10万]",
				value: "(0,10万]",
				colField: "",
				name: "他行授信额度#保证#(0,10万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100303",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "他行授信额度#保证#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100304",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "他行授信额度#保证#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100305",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "他行授信额度#保证#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100306",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "他行授信额度#保证#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100307",
				title: "自定义",
				value: "",
				colField: "",
				name: "他行授信额度#保证",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02100400",
			title: "抵押",
			value: "抵押",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "取最近一次线上征信报告上授信到期日晚于当前日期的所有贷款汇总",
			list: [{
				code: "02100401",
				title: "0",
				value: "0",
				colField: "",
				name: "他行授信额度#抵押#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100402",
				title: "(0,10万]",
				value: "(0,10万]",
				colField: "",
				name: "他行授信额度#抵押#(0,10万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100403",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "他行授信额度#抵押#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100404",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "他行授信额度#抵押#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100405",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "他行授信额度#抵押#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100406",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "他行授信额度#抵押#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100407",
				title: "自定义",
				value: "",
				colField: "",
				name: "他行授信额度#抵押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02100500",
			title: "质押",
			value: "质押",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "取最近一次线上征信报告上授信到期日晚于当前日期的所有贷款汇总",
			list: [{
				code: "02100501",
				title: "0",
				value: "0",
				colField: "",
				name: "他行授信额度#质押#0",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100502",
				title: "(0,10万]",
				value: "(0,10万]",
				colField: "",
				name: "他行授信额度#质押#(0,10万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100503",
				title: "(10万,30万]",
				value: "(10万,30万]",
				colField: "",
				name: "他行授信额度#质押#(10万,30万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100504",
				title: "(30万,60万]",
				value: "(30万,60万]",
				colField: "",
				name: "他行授信额度#质押#(30万,60万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100505",
				title: "(60万,200万]",
				value: "(60万,200万]",
				colField: "",
				name: "他行授信额度#质押#(60万,200万]",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100506",
				title: "＞200万",
				value: "＞200万",
				colField: "",
				name: "他行授信额度#质押#＞200万",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "02100507",
				title: "自定义",
				value: "",
				colField: "",
				name: "他行授信额度#质押",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}, {
			code: "02100600",
			title: "无数据",
			value: "无数据",
			colField: "",
			name: "他行授信额度#无数据",
			minValue: "",
			maxValue: "",
			remark: "无线上查询记录",
			list: []
		}]
	}, {
		code: "02110000",
		title: "他行授信到期日",
		value: "他行授信到期日",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取最近一次线上贷款征信报告的他行授信到期日数据",
		list: [{
			code: "02110100",
			title: "≤30天",
			value: "≤30天",
			colField: "TH_CRDT_EXP_DAY",
			name: "他行授信到期日#≤30天",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02110200",
			title: "(30天,60天]",
			value: "(30天,60天]",
			colField: "TH_CRDT_EXP_DAY",
			name: "他行授信到期日#(30天,60天]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02110300",
			title: "(60天,90天]",
			value: "(60天,90天]",
			colField: "TH_CRDT_EXP_DAY",
			name: "他行授信到期日#(60天,90天]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02110400",
			title: "＞90天",
			value: "＞90天",
			colField: "TH_CRDT_EXP_DAY",
			name: "他行授信到期日#＞90天",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02110500",
			title: "自定义",
			value: "",
			colField: "TH_CRDT_EXP_DAY",
			name: "他行授信到期日",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "02120000",
		title: "人行征信分",
		value: "人行征信分",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取最近一次贷前或贷后线上查询获取的人行征信分，若无线上查询记录，则此项为空",
		list: [{
			code: "02120100",
			title: "白户或-1",
			value: "白户或-1",
			colField: "RH_CRED_SCRO",
			name: "人行征信分#白户或-1",
			minValue: "",
			maxValue: "",
			remark: "客户征信无贷款记录或征信分显示为-1",
			list: []
		}, {
			code: "02120200",
			title: "[0,750)",
			value: "[0,750)",
			colField: "RH_CRED_SCRO",
			name: "人行征信分#[0,750)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02120300",
			title: "[750,790)",
			value: "[750,790)",
			colField: "RH_CRED_SCRO",
			name: "人行征信分#[750,790)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02120400",
			title: "[790,840)",
			value: "[790,840)",
			colField: "RH_CRED_SCRO",
			name: "人行征信分#[790,840)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02120500",
			title: "[840,880)",
			value: "[840,880)",
			colField: "RH_CRED_SCRO",
			name: "人行征信分#[840,880)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02120600",
			title: "≥880",
			value: "≥880",
			colField: "RH_CRED_SCRO",
			name: "人行征信分#≥880",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "02120700",
			title: "自定义",
			value: "",
			colField: "RH_CRED_SCRO",
			name: "人行征信分",
			minValue: "",
			maxValue: "",
			remark: "范围[-1,1000]",
			list: []
		}, {
			code: "02120800",
			title: "无数据",
			value: "无数据",
			colField: "RH_CRED_SCRO",
			name: "人行征信分#无数据",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}]
}, {
	code: "03000000",
	title: "商户指标",
	value: "商户指标",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "03010000",
		title: "店员人数",
		value: "店员人数",
		colField: "SHOP_NUM",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取九银店老板中商户绑定的店员人数",
		list: []
	}, {
		code: "03020000",
		title: "行业MCC码",
		value: "行业MCC码",
		colField: "MCC_CODE",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "商户MCC码",
		list: []
	}, {
		code: "03030000",
		title: "是否有效商户",
		value: "是否有效商户",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "符合当年有效商户考核口径的商户",
		list: [{
			code: "03030100",
			title: "是",
			value: "是",
			colField: "IS_EFF_MRCH",
			name: "是否有效商户#是",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03030200",
			title: "否",
			value: "否",
			colField: "IS_EFF_MRCH",
			name: "是否有效商户#否",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "03040000",
		title: "年交易额",
		value: "年交易额",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "当年度单个商户号对应的累计交易金额，单位为元",
		list: [{
			code: "03040100",
			title: "＜1000",
			value: "＜1000",
			colField: "MRCH_TRAN_AMT_YEAR",
			name: "年交易额#＜1000",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03040200",
			title: "[1000,2000)",
			value: "[1000,2000)",
			colField: "MRCH_TRAN_AMT_YEAR",
			name: "年交易额#[1000,2000)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03040300",
			title: "[2000,20000)",
			value: "[2000,20000)",
			colField: "MRCH_TRAN_AMT_YEAR",
			name: "年交易额#[2000,20000)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03040400",
			title: "≥20000",
			value: "≥20000",
			colField: "MRCH_TRAN_AMT_YEAR",
			name: "年交易额#≥20000",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03040500",
			title: "自定义",
			value: "",
			colField: "MRCH_TRAN_AMT_YEAR",
			name: "年交易额",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "03050000",
		title: "年交易天数",
		value: "年交易天数",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "当年度单个商户号对应的累计交易天数",
		list: [{
			code: "03050100",
			title: "＜8",
			value: "＜8",
			colField: "MRCH_TRAN_DAY_YEAR",
			name: "年交易天数#＜8",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03050200",
			title: "[8,12)",
			value: "[8,12)",
			colField: "MRCH_TRAN_DAY_YEAR",
			name: "年交易天数#[8,12)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03050300",
			title: "[12,120)",
			value: "[12,120)",
			colField: "MRCH_TRAN_DAY_YEAR",
			name: "年交易天数#[12,120)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03050400",
			title: "≥120天",
			value: "≥120天",
			colField: "MRCH_TRAN_DAY_YEAR",
			name: "年交易天数#≥120天",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03050500",
			title: "自定义",
			value: "",
			colField: "MRCH_TRAN_DAY_YEAR",
			name: "年交易天数",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "03060000",
		title: "上月交易额",
		value: "上月交易额",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "上月单个商户号对应的累计交易金额",
		list: [{
			code: "03060100",
			title: "＜1000",
			value: "＜1000",
			colField: "MRCH_TRAN_AMT_LM",
			name: "上月交易额#＜1000",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03060200",
			title: "[1000,2000)",
			value: "[1000,2000)",
			colField: "MRCH_TRAN_AMT_LM",
			name: "上月交易额#[1000,2000)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03060300",
			title: "≥2000",
			value: "≥2000",
			colField: "MRCH_TRAN_AMT_LM",
			name: "上月交易额#≥2000",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03060400",
			title: "自定义",
			value: "",
			colField: "MRCH_TRAN_AMT_LM",
			name: "上月交易额",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "03070000",
		title: "上月交易天数",
		value: "上月交易天数",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "上月单个商户号对应的累计交易天数",
		list: [{
			code: "03070100",
			title: "≥12",
			value: "≥12",
			colField: "MRCH_TRAN_DAY_LM",
			name: "上月交易天数#≥12",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03070200",
			title: "＜12",
			value: "＜12",
			colField: "MRCH_TRAN_DAY_LM",
			name: "上月交易天数#＜12",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03070300",
			title: "自定义",
			value: "",
			colField: "MRCH_TRAN_DAY_LM",
			name: "上月交易天数",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "03080000",
		title: "收单活期留存率",
		value: "收单活期留存率",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "广义活期上月月日均与近12个月月均交易金额之比（若办理收单月份数不足12个月，取实际月份数）",
		list: [{
			code: "03080100",
			title: "＜1%",
			value: "＜1%",
			colField: "MRCH_CURR_DPSIT_RATE",
			name: "收单活期留存率#＜1%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03080200",
			title: "[1%,10%)",
			value: "[1%,10%)",
			colField: "MRCH_CURR_DPSIT_RATE",
			name: "收单活期留存率#[1%,10%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03080300",
			title: "[10%,50%)",
			value: "[10%,50%)",
			colField: "MRCH_CURR_DPSIT_RATE",
			name: "收单活期留存率#[10%,50%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03080400",
			title: "[50%,100%)",
			value: "[50%,100%)",
			colField: "MRCH_CURR_DPSIT_RATE",
			name: "收单活期留存率#[50%,100%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03080500",
			title: "≥100%",
			value: "≥100%",
			colField: "MRCH_CURR_DPSIT_RATE",
			name: "收单活期留存率#≥100%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03080600",
			title: "自定义",
			value: "",
			colField: "MRCH_CURR_DPSIT_RATE",
			name: "收单活期留存率",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "03090000",
		title: "收单AUM留存率",
		value: "收单AUM留存率",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "广义AUM上月月日均与近12个月月均交易金额之比（若办理收单月份数不足12个月，取实际月份数）",
		list: [{
			code: "03090100",
			title: "＜1%",
			value: "＜1%",
			colField: "MRCH_AUM_RATE",
			name: "收单AUM留存率#＜1%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03090200",
			title: "[1%,10%)",
			value: "[1%,10%)",
			colField: "MRCH_AUM_RATE",
			name: "收单AUM留存率#[1%,10%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03090300",
			title: "[10%,50%)",
			value: "[10%,50%)",
			colField: "MRCH_AUM_RATE",
			name: "收单AUM留存率#[10%,50%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03090400",
			title: "[50%,100%)",
			value: "[50%,100%)",
			colField: "MRCH_AUM_RATE",
			name: "收单AUM留存率#[50%,100%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03090500",
			title: "≥100%",
			value: "≥100%",
			colField: "MRCH_AUM_RATE",
			name: "收单AUM留存率#≥100%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03090600",
			title: "自定义",
			value: "",
			colField: "MRCH_AUM_RATE",
			name: "收单AUM留存率",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "03100000",
		title: "收单综合贡献度",
		value: "收单综合贡献度",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "从交易笔数（10笔/分,共20）、交易金额（300元/分,共20）、商户存款（5000元/分,共40）贷款（15000元/分）四个维度共100分来描述一个商户在我行的贡献",
		list: [{
			code: "03100100",
			title: "[0,40]",
			value: "[0,40]",
			colField: "MRCH_CMPRH_CONTRI",
			name: "收单综合贡献度#[0,40]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03100200",
			title: "(40,80]",
			value: "(40,80]",
			colField: "MRCH_CMPRH_CONTRI",
			name: "收单综合贡献度#(40,80]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03100300",
			title: "(80,100]",
			value: "(80,100]",
			colField: "MRCH_CMPRH_CONTRI",
			name: "收单综合贡献度#(80,100]",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "03100400",
			title: "自定义",
			value: "",
			colField: "MRCH_CMPRH_CONTRI",
			name: "收单综合贡献度",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}]
}, {
	code: "04000000",
	title: "代发指标",
	value: "代发指标",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "04010000",
		title: "代发单位",
		value: "代发单位",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取核心代发单位字段",
		list: []
	}, {
		code: "04020000",
		title: "代发次数",
		value: "代发次数",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "当年代发次数",
		list: [{
			code: "04020100",
			title: "＜5",
			value: "＜5",
			colField: "AGENT_CNT",
			name: "代发次数#＜5",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04020200",
			title: "[5,8)",
			value: "[5,8)",
			colField: "AGENT_CNT",
			name: "代发次数#[5,8)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04020300",
			title: "[8,12)",
			value: "[8,12)",
			colField: "AGENT_CNT",
			name: "代发次数#[8,12)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04020400",
			title: "≥12",
			value: "≥12",
			colField: "AGENT_CNT",
			name: "代发次数#≥12",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04020500",
			title: "自定义",
			value: "",
			colField: "AGENT_CNT",
			name: "代发次数",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "04030000",
		title: "当年代发金额",
		value: "当年代发金额",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "当年代发累计金额",
		list: [{
			code: "04030100",
			title: "＜15000",
			value: "＜15000",
			colField: "AGENT_AMT",
			name: "当年代发金额#＜15000",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04030200",
			title: "[15000,25000)",
			value: "[15000,25000)",
			colField: "AGENT_AMT",
			name: "当年代发金额#[15000,25000)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04030300",
			title: "[25000,50000)",
			value: "[25000,50000)",
			colField: "",
			name: "当年代发金额#[25000,50000)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04030400",
			title: "[50000,100000)",
			value: "[50000,100000)",
			colField: "AGENT_AMT",
			name: "当年代发金额#[50000,100000)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04030500",
			title: "≥100000",
			value: "≥100000",
			colField: "AGENT_AMT",
			name: "当年代发金额#≥100000",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04030600",
			title: "自定义",
			value: "",
			colField: "AGENT_AMT",
			name: "当年代发金额",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "04040000",
		title: "当年月均代发金额",
		value: "当年月均代发金额",
		colField: "AGENT_AMT_MONTH_AVG",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "当年月均代发金额（当年代发总金额/代发月份总数）",
		list: []
	}, {
		code: "04050000",
		title: "代发活期留存率",
		value: "代发活期留存率",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "广义活期上月月日均与近12个月月均代发金额之比（若近12个月代发月份数不足12个月，取实际代发月数）",
		list: [{
			code: "04050100",
			title: "＜1.5%",
			value: "＜1.5%",
			colField: "AGENT_CURR_DPSIT_RATE",
			name: "代发活期留存率#＜1.5%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04050200",
			title: "[1.5%,6%)",
			value: "[1.5%,6%)",
			colField: "AGENT_CURR_DPSIT_RATE",
			name: "代发活期留存率#[1.5%,6%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04050300",
			title: "[6%,20%)",
			value: "[6%,20%)",
			colField: "AGENT_CURR_DPSIT_RATE",
			name: "代发活期留存率#[6%,20%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04050400",
			title: "[20%,50%)",
			value: "[20%,50%)",
			colField: "AGENT_CURR_DPSIT_RATE",
			name: "代发活期留存率#[20%,50%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04050500",
			title: "[50%,70%)",
			value: "[50%,70%)",
			colField: "AGENT_CURR_DPSIT_RATE",
			name: "代发活期留存率#[50%,70%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04050600",
			title: "≥70%",
			value: "≥70%",
			colField: "AGENT_CURR_DPSIT_RATE",
			name: "代发活期留存率#≥70%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04050700",
			title: "自定义",
			value: "",
			colField: "AGENT_CURR_DPSIT_RATE",
			name: "代发活期留存率",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "04060000",
		title: "代发AUM留存率",
		value: "代发AUM留存率",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "广义AUM上月月日均与近12个月月均代发金额之比（若近12个月代发月份数不足12个月，取实际代发月数）",
		list: [{
			code: "04060100",
			title: "＜1.5%",
			value: "＜1.5%",
			colField: "AGENT_AUM_RATE",
			name: "代发AUM留存率#＜1.5%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04060200",
			title: "[1.5%,6%)",
			value: "[1.5%,6%)",
			colField: "AGENT_AUM_RATE",
			name: "代发AUM留存率#[1.5%,6%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04060300",
			title: "[6%,30%)",
			value: "[6%,30%)",
			colField: "AGENT_AUM_RATE",
			name: "代发AUM留存率#[6%,30%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04060400",
			title: "[30%,60%)",
			value: "[30%,60%)",
			colField: "AGENT_AUM_RATE",
			name: "代发AUM留存率#[30%,60%)",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04060500",
			title: "≥60%",
			value: "≥60%",
			colField: "AGENT_AUM_RATE",
			name: "代发AUM留存率#≥60%",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "04060600",
			title: "自定义",
			value: "",
			colField: "AGENT_AUM_RATE",
			name: "代发AUM留存率",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "04070000",
		title: "同名划转率",
		value: "同名划转率",
		colField: "TM_TRAN_RATE",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "最近一次代发工资后7天内同名划转至他行的总金额与本次代发金额比值",
		list: []
	}]
}, {
	code: "05000000",
	title: "资产指标",
	value: "资产指标",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "05010000",
		title: "AUM年日均",
		value: "AUM年日均",
		colField: "AUM_YEAR_AVG",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "当年度1月1日至上月底的广义AUM资产累计值与统计时间段内总天数之比",
		list: [{
			code: "05010100",
			title: "全部",
			value: "全部",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05010200",
			title: "定期",
			value: "定期",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05010300",
			title: "活期",
			value: "活期",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05010400",
			title: "理财",
			value: "理财",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05010500",
			title: "信托",
			value: "信托",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05010600",
			title: "基金",
			value: "基金",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05010700",
			title: "保险",
			value: "保险",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "05020000",
		title: "AUM月日均",
		value: "AUM月日均",
		colField: "AUM_MONTH_AVG",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "上月每日的广义AUM资产累计值与上月天数之比",
		list: [{
			code: "05020100",
			title: "全部",
			value: "全部",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05020200",
			title: "定期",
			value: "定期",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05020300",
			title: "活期",
			value: "活期",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05020400",
			title: "理财",
			value: "理财",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05020500",
			title: "信托",
			value: "信托",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05020600",
			title: "基金",
			value: "基金",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05020700",
			title: "保险",
			value: "保险",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "05030000",
		title: "AUM余额",
		value: "AUM余额",
		colField: "AUM_BAL",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "当前广义AUM余额数据",
		list: [{
			code: "05030100",
			title: "全部",
			value: "全部",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05030200",
			title: "定期",
			value: "定期",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05030300",
			title: "活期",
			value: "活期",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05030400",
			title: "理财",
			value: "理财",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05030500",
			title: "信托",
			value: "信托",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05030600",
			title: "基金",
			value: "基金",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "05030700",
			title: "保险",
			value: "保险",
			colField: "",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "05040000",
		title: "近3月三方理财购买额",
		value: "近3月三方理财购买额",
		colField: "TPTY_CFT_BUY_3M",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "近3月客户用我行卡购买的三方理财总金额（三方理财定义为金融交易流水中对方客户名称包含“理财”、“基金**有限”字样）",
		list: []
	}, {
		code: "05050000",
		title: "极差值",
		value: "极差值",
		colField: "AUM_DIF_VAL",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "近一年广义AUM余额最高值与当前余额差值",
		list: []
	}]
}, {
	code: "06000000",
	title: "签约指标",
	value: "签约指标",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "06010000",
		title: "产品签约",
		value: "产品签约",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取客户在我行产品签约信息",
		list: [{
			code: "06010100",
			title: "理财",
			value: "理财",
			colField: "PRO_SIGN",
			name: "产品签约#理财",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06010200",
			title: "基金",
			value: "基金",
			colField: "PRO_SIGN",
			name: "产品签约#基金",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "06020000",
		title: "渠道签约",
		value: "渠道签约",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取我行卡渠道签约信息",
		list: [{
			code: "06020100",
			title: "手机银行",
			value: "手机银行",
			colField: "CHN_SIGN",
			name: "渠道签约#手机银行",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06020200",
			title: "支付宝",
			value: "支付宝",
			colField: "CHN_SIGN",
			name: "渠道签约#支付宝",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06020300",
			title: "微信支付",
			value: "微信支付",
			colField: "CHN_SIGN",
			name: "渠道签约#微信支付",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06020400",
			title: "云闪付",
			value: "云闪付",
			colField: "CHN_SIGN",
			name: "渠道签约#云闪付",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06020500",
			title: "久赢合伙人",
			value: "久赢合伙人",
			colField: "CHN_SIGN",
			name: "渠道签约#久赢合伙人",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06020600",
			title: "网上银行",
			value: "网上银行",
			colField: "CHN_SIGN",
			name: "渠道签约#网上银行",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06020700",
			title: "微信银行",
			value: "微信银行",
			colField: "CHN_SIGN",
			name: "渠道签约#微信银行",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}, {
		code: "06030000",
		title: "信用卡持有标志",
		value: "信用卡持有标志",
		colField: "CARD_SIGN",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "是否持有我行信用卡",
		list: [{
			code: "06030100",
			title: "否",
			value: "否",
			colField: "CARD_SIGN",
			name: "信用卡持有标志#否",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}, {
			code: "06030200",
			title: "是",
			value: "是",
			colField: "CARD_SIGN",
			name: "",
			minValue: "",
			maxValue: "",
			remark: "根据持有我行信用卡客户是否绑定我行借记卡还款数据判断",
			list: [{
				code: "06030201",
				title: "全部",
				value: "全部",
				colField: "",
				name: "信用卡持有标志#是#全部",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "06030202",
				title: "是",
				value: "是",
				colField: "",
				name: "信用卡持有标志#是#是",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}, {
				code: "06030203",
				title: "否",
				value: "否",
				colField: "",
				name: "信用卡持有标志#是#否",
				minValue: "",
				maxValue: "",
				remark: "",
				list: []
			}]
		}]
	}, {
		code: "06040000",
		title: "缴费签约",
		value: "缴费签约",
		colField: "",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取客户在我行缴费签约信息",
		list: [{
			code: "06040100",
			title: "电费",
			value: "电费",
			colField: "PTF_SIGN",
			name: "渠道签约#电费",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06040100",
			title: "水费",
			value: "水费",
			colField: "PTF_SIGN",
			name: "渠道签约#水费",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		},{
			code: "06040100",
			title: "燃气费",
			value: "燃气费",
			colField: "PTF_SIGN",
			name: "渠道签约#燃气费",
			minValue: "",
			maxValue: "",
			remark: "",
			list: []
		}]
	}]
}, {
	code: "07000000",
	title: "交易指标",
	value: "交易指标",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "07010000",
		title: "月动账次数",
		value: "月动账次数",
		colField: "DYNA_ACCT_CNT_MONT",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "近1个月客户名下我行个人账户（含信用卡）动账次数汇总数",
		list: []
	}, {
		code: "07020000",
		title: "近1年信用卡交易笔数",
		value: "近1年信用卡交易笔数",
		colField: "CARD_TRAN_CNT_1Y",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "近1年客户名下我行信用卡动账次数汇总数",
		list: []
	}]
}, {
	code: "08000000",
	title: "手机银行指标",
	value: "手机银行指标",
	colField: "",
	name: "",
	minValue: "",
	maxValue: "",
	remark: "",
	list: [{
		code: "08010000",
		title: "近1月理财专区浏览次数",
		value: "近1月理财专区浏览次数",
		colField: "CFT_BROWSE_CNT_1M",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取近1个月理财专区（含基金）浏览次数（单次停留超30s计为1次有效次数）",
		list: []
	}, {
		code: "08020000",
		title: "近1月贷款专区浏览次数",
		value: "近1月贷款专区浏览次数",
		colField: "LOAN_BROWSE_CNT_1M",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取近1个月贷款专区浏览次数（单次停留超30s计为1次有效次数）",
		list: []
	}, {
		code: "08030000",
		title: "手机银行近60天日活率",
		value: "手机银行近60天日活率",
		colField: "PBANK_AC_RATE_60D",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取近60天登录手机银行次数（按天去重）与60天比值",
		list: []
	}, {
		code: "08040000",
		title: "手机银行活动近60天参与次数",
		value: "手机银行活动近60天参与次数",
		colField: "PBANK_PRTCPTN_CNT_60D",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取客户近60天手机银行活动参与次数",
		list: []
	}, {
		code: "08050000",
		title: "权益领取标志",
		value: "权益领取标志",
		colField: "EQTY_DRAW_FLG",
		name: "",
		minValue: "",
		maxValue: "",
		remark: "取客户当月权益是否领取数据",
		list: []
	}]
}]
